config/routes.rb
Bk::Application.routes.draw do

  get "event_images/index"

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: 'authentications#failure'
  match 'auth/:provider/returning', to: 'authentications#returning'
  get 'authentications' => 'authentications#index'
  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'home' => 'users#show'
  get 'edit' => 'users#edit'
  get 'activities' => 'activities#index'
  match '/activities/:activity_id/places/:place_id/images(.:format)', to: 'place_images#index'
  get '/users/:user_id/images(.:format)', to: 'user_images#index'
  get '/users/:user_id/images/:id(.:format)', to: 'user_images#update'
  match '/activities/:activity_id/places/:place_id/events/:id(.:format)', to: 'place_events#show'
  
  post '/users/:user_id/images(.:format)' => 'user_images#create', as: :new_user_image
  delete '/users/:user_id/images/:id(.:format)' => 'user_images#destroy'
  
  get '/activities/:activity_id/places/:place_id/events/:id/images(.:format)', to: 'event_images#index'

  
  resources :sessions
  resources :interests
  resources :password_resets
  
  resources :activities do
    resources :places do
      resources :images
      resources :events do
        resources :images
      end
    end
  end
  
  resources :users do
    resources :interests
    resources :activities
    resources :events
    resources :comments
    resources :images
  end
  
  
  

  root :to => "sessions#new"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :user_id, :user_rating
  has_many :interests
  has_many :users, :through => :interests
  has_many :places
  has_many :images
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :image_url, :provider, :sent_at, :uid
  belongs_to :user
  validates :provider, uniqueness: { scope: :uid }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :place_id, :text, :user_id, :event_id
  belongs_to :user
  belongs_to :place
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :place_id, :recurring, :time, :title
  has_many :comments
  has_many :images
  belongs_to :place
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :type, :url, :place_id, :event_id, :user_id, :activity_id, :rating, :image_type, :title, :description, :image, :remote_image_url
  belongs_to :place
  belongs_to :activity
  belongs_to :user
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  attr_accessible :activity_id, :user_rating
  validates :activity_id, uniqueness: { scope: :user_id }
end

app/models/permissions.rb
module Permissions
  def self.permission_for(user)
    if user.nil?
      GuestPermission.new
    elsif user.is_admin?
      AdminPermission.new(user)
    else
      MemberPermission.new(user)
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :activity_id, :directions, :hours, :location, :zip_code
  has_many :comments
  has_many :images
  has_many :events
  belongs_to :activity
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_many :interests
  has_many :activities, :through => :interests
  has_many :authentications
  has_many :comments
  has_many :images
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation, :zip_code, :is_admin, :username
  validates_uniqueness_of :email
  validates :email, :presence => true, :email => true
  #validates :password, :length => { :minimum => 8 }
  # each User.new creates calls generate_token and stores it in :auth_token
  before_create { generate_token(:auth_token) }
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  
end

app/controllers/user_images_controller.rb
class UserImagesController < ApplicationController
  def index
    @banner_images = Image.where(user_id: current_user, image_type: 'banner')
    @default_images = Image.where(user_id: current_user, image_type: 'default')
    @image = Image.new
  end

  def update
    @image = current_resource
    if @image.update_attributes(params[:image])
      flash[:notice] = 'Image updated'
    else
      flash[:notice] = 'Error updating image'
    end
  end
  
  def create
    @image = current_user.images.build(params[:image])
    @image.rating = 0
    if @image.save
      flash[:notice] = 'Image added'
    else
      flash[:notice] = 'Error adding Image'
    end
    respond_to do |format|
      format.js { render 'update' }
    end
  end
  
  def destroy
    @image = current_resource
    if @image.destroy
      flash[:notice] = 'Image deleted'
    else
      flash[:notice] = 'Error deleting image'
    end
    respond_to do |format|
      format.js { render 'update' }
    end
  end

private
  def current_resource
    @current_resource ||= current_user.images.find(params[:id]) if params[:id]
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activties_helper.rb
module ActivtiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_images_helper.rb
module EventImagesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  # Flash Helper
  def flash_display
    response = ""
    flash.each do |name, msg|
      response = response + content_tag(:div, msg, :id => "flash_#{name}")
    end
    response.insert(0, "<i class='icon-remove pull-right' id='flash-exit'></i>" )
    flash.discard
    response
  end
  
end

app/helpers/place_events_helper.rb
module PlaceEventsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user_images/_banner_images.html.erb
<figure class='user-image-banner-figure'>  
<%= image_tag image.image_url(:banner), class: 'image-banner' if image.image? %>
<figcaption class='hover-gray toggle-update-form'>
  <section class='pull-right form-toggle hide'><i class='icon-remove toggle-remove close-figcap' ></i></section>
  <small>
  <p>
    <%= form_for [current_user, image], remote: true do |f| %>
    <% activities_array = Activity.all.map { |activity| [activity.name, activity.id] } %>
    <strong>Activity: </strong><span class='form-toggle'><%= image.activity.name if image.activity %></span>
    <span class='form-toggle hide'><%= f.select(:activity_id, options_for_select(activities_array, image.activity.id), {}, class: 'input-medium image-activity') %></span><br>
    
    <strong>Rating: </strong><%= image.rating %><br>
    <strong>Title: </strong><span class='form-toggle'><%= image.title %></span>
    <span class='form-toggle hide'><%= f.text_field :title, class: 'input-medium' %></span><br>
    
    <strong>Description: </strong><span class='form-toggle'><%= image.description %></span>
    <span class='form-toggle hide'><%= f.text_field :description, class: 'input-xlarge' %></span><br>
    
    <span class='form-toggle hide'><strong>Url: </strong><%= image.image %></span><br>
    <section class='float-left'>
      <%= f.submit 'Update', class: 'btn user-img-update-btn form-toggle hide float-left' %>
      <%= link_to 'Delete', user_image_path(current_user,image), class: 'pull-right btn btn-danger form-toggle hide', method: 'delete', remote: true, confirm: 'Are you sure?' %>
  </section>
    <% end %>
    
  </p>
</small>
</figcation>
</figure>

app/views/user_images/_default_images.html.erb
<figure class='user-image-default-figure'>
  <figcaption>
    <%= link_to 'Delete', user_image_path(current_user,image), method: 'delete', remote: true, confirm: 'Are you sure?' %>
  </figcaption>
  <% if image.image? %>
    <%= image_tag image.image_url(:thumb), class: 'image-thumbnail' %>
    <%= image_tag image.image_url(:gallery), class: 'image-gallery' %>
    <%= image_tag image.image_url(:default), class: 'image-default'%>
  <% end %>
<figcaption class='hover-gray toggle-update-form'>
  <section class='pull-right form-toggle hide'><i class='icon-remove toggle-remove close-figcap' ></i></section>
  <small>
  <p>
    <%= form_for [current_user, image], remote: true do |f| %>
    <strong>Place:</strong> <%= image.place.title if image.place %><br>
    <strong>Event:</strong> <%= image.event.title if image.event %><br>
    <strong>Rating:</strong> <%= image.rating %><br>
        
    <strong>Title: </strong><span class='form-toggle'><%= image.title %></span>
    <span class='form-toggle hide'><%= f.text_field :title, class: 'input-medium' %></span><br>
    
    <strong>Description: </strong><span class='form-toggle'><%= image.description %></span>
    <span class='form-toggle hide'><%= f.text_field :description, class: 'input-xlarge' %></span><br>
    <span class='form-toggle hide'><strong>Url: </strong><%= root_url %><%= image.image %></span><br>
    
    <span><%= f.submit 'Update', class: 'btn form-toggle hide user-img-update-btn' %></span>
    <% end %>
  </p>
</small>
</figcation>
</figure>

app/views/user_images/index.html.erb
<h1>Images</h1>

<h3>Activity Images</h3>
<section id='banner-images-wrap'>
  <%= render partial: 'banner_images', collection: @banner_images, as: :image %>
</section>

<h3 class='clear-both'>Place Images</h3>
<section id='default-images-wrap'>
  <%= render partial: 'default_images', collection: @default_images, as: :image %>
  <section class='new-user-image'>
    <% activities_array = Activity.all.map { |activity| [activity.name, activity.id] } %>
    <% places_array = Place.all.map { |place| [place.title, place.id] } %>
    <% events_array = Event.all.map { |event| [event.title, event.id] }%>
    <% image_types_array = ['default','banner'] %>
    <!-- edit url needs to got to  -->
    <%= form_for [current_user, @image], remote: true, html: { multipart: true } do |f| %>
    <%= f.file_field :image %>
      <%= f.text_field :remote_image_url, class: 'input-x-large', placeholder: 'URL' %>
      <%= f.select(:activity_id, options_for_select(activities_array), { include_blank: true }, class: 'input-medium image-activity') %>
      <%= f.select(:place_id, options_for_select(places_array), { include_blank: true }, class: 'input-medium image-activity') %>
      <%= f.select(:event_id, options_for_select(events_array), { include_blank: true }, class: 'input-medium image-activity') %>
      <%= f.select(:image_type, options_for_select(image_types_array), { include_blank: true }, class: 'input-medium image-activity') %>
      <%= f.text_field :title, class: 'input-medium', placeholder: 'Title'  %>
      <%= f.text_area :description, size: '100x2', placeholder: 'Description' %>
      <%= f.submit 'Upload', class: 'btn' %>
    <% end %>
  </section>
</section>