config/routes.rb
Bk::Application.routes.draw do

  get "event_images/index"

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: 'authentications#failure'
  match 'auth/:provider/returning', to: 'authentications#returning'
  get 'authentications' => 'authentications#index'
  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'home' => 'users#show'
  get 'edit' => 'users#edit'
  get 'activities' => 'activities#index'
  match '/activities/:activity_id/places/:place_id/images(.:format)', to: 'place_images#index'
  get '/users/:user_id/images(.:format)', to: 'user_images#index'
  get '/users/:user_id/images/:id(.:format)', to: 'user_images#update'
  match '/activities/:activity_id/places/:place_id/events/:id(.:format)', to: 'place_events#show'
  
  post '/users/:user_id/images(.:format)' => 'user_images#create', as: :new_user_image
  delete '/users/:user_id/images/:id(.:format)' => 'user_images#destroy'
  
  get '/activities/:activity_id/places/:place_id/events/:id/images(.:format)', to: 'event_images#index'

  
  resources :sessions
  resources :interests
  resources :password_resets
  
  resources :activities do
    resources :places do
      resources :images
      resources :events do
        resources :images
      end
    end
  end
  
  resources :users do
    resources :interests
    resources :activities
    resources :events
    resources :comments
    resources :images
  end
  
  
  

  root :to => "sessions#new"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :user_id, :user_rating
  has_many :interests
  has_many :users, :through => :interests
  has_many :places
  has_many :images
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :image_url, :provider, :sent_at, :uid
  belongs_to :user
  validates :provider, uniqueness: { scope: :uid }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :place_id, :text, :user_id, :event_id
  belongs_to :user
  belongs_to :place
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :place_id, :recurring, :time, :title
  has_many :comments
  has_many :images
  belongs_to :place
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :type, :url, :place_id, :event_id, :user_id, :activity_id, :rating, :image_type, :title, :description, :image, :remote_image_url
  belongs_to :place
  belongs_to :activity
  belongs_to :user
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  attr_accessible :activity_id, :user_rating
  validates :activity_id, uniqueness: { scope: :user_id }
end

app/models/permissions.rb
module Permissions
  def self.permission_for(user)
    if user.nil?
      GuestPermission.new
    elsif user.is_admin?
      AdminPermission.new(user)
    else
      MemberPermission.new(user)
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :activity_id, :directions, :hours, :location, :zip_code
  has_many :comments
  has_many :images
  has_many :events
  belongs_to :activity
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_many :interests
  has_many :activities, :through => :interests
  has_many :authentications
  has_many :comments
  has_many :images
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation, :zip_code, :is_admin, :username
  validates_uniqueness_of :email
  validates :email, :presence => true, :email => true
  #validates :password, :length => { :minimum => 8 }
  # each User.new creates calls generate_token and stores it in :auth_token
  before_create { generate_token(:auth_token) }
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  
  
  def new
    @activities = Activity.all
    @user = current_user
    @interest = Interest.new
  end
  
  def create
    @interest = current_user.interests.build(params[:interest])
    if @interest.save 
      flash[:notice] = "#{(Activity.where(id: @interest.activity_id).first.name)} was added to your interests"
    else
      flash[:notice] = "Error occurred while trying to add #{(Activity.where(id: @interest.activity_id).first.name)} to your interests"
    end 
    respond_to do |format|
      format.html { if @interest.save then redirect_to home_path else render "new" end }
      format.js { render 'update' }
    end
  end
  
  def update
    @interest = current_resource
    if @interest.update_attributes(params[:interest])
      flash[:notice] = "Your rating for #{@interest.activity.name} was updated to #{@interest.user_rating}"
    else
      flash[:notice] = "Error occurred while trying to update your rating for #{@interest.activity.name}"
    end
    respond_to do |format|
      format.html
      format.js 
    end
  end
  
  def destroy
    @interest = current_resource
    activity = @interest.activity
    if @interest.destroy
      flash[:notice] = "#{activity.name} was removed to your interests"
    else
      flash[:notice] = "Error occured while trying to remove #{activity.name} from your interests"
    end
    respond_to do |format|
      format.html { redirect_to home_path }
      format.js { render 'update' }
    end
  end

private
  
  def current_resource
    @current_resource ||= Interest.find(params[:id]) if params[:id]
  end
  
    
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activties_helper.rb
module ActivtiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_images_helper.rb
module EventImagesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  # Flash Helper
  def flash_display
    response = ""
    flash.each do |name, msg|
      response = response + content_tag(:div, msg, :id => "flash_#{name}")
    end
    response.insert(0, "<i class='icon-remove pull-right' id='flash-exit'></i>" )
    flash.discard
    response
  end
  
end

app/helpers/place_events_helper.rb
module PlaceEventsHelper
end

app/helpers/place_images_helper.rb
module PlaceImagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/interests/_add_interest.html.erb
<% unless current_user.activities.include?(activity) %>
	<section class='activity-option' data-activity='<%= activity.id %>'>
		<span class='optional-activity-name on-click lead'><%= activity.name %></span>
		<%= form_for Interest.new, remote: true, html: { class: 'new_interest inline remote' } do |f| %>
  		<% activities_array = Activity.all.map { |activity| [activity.name, activity.id] } %>
      <%= f.select(:activity_id, options_for_select((activities_array),activity.id),{}, class: 'hide')%>
  		<%= f.select(:user_rating, options_for_select((1..10)),{ :include_blank => true }, data: { activity_id: activity.id }, 
        class: 'input-xmini input-mini' ) %>
  		<%= f.submit 'Update', class: 'btn' %>
		<% end %>
	</section>
<% end %>

app/views/interests/_user_interests.html.erb
<% a = Activity.where(:id => interest.activity_id).first %>

<section class='current-user-activity' data-activity-id='<%= a.id %>' data-interest-id='<%= interest.id %>'>
	<section class='float-left'>
		<span class='on-click current-activity-name lead' data-activity-id='<%= a.id %>'><%= a.name %></span>
		<!--<span class='current-activity-user-rating' data-activity-id='<%= a.id %>'><%= interest.user_rating %></span> -->
	</section>
	<section class='float-left height-mini'>
		<%= form_for interest, remote: true, html: { class: 'edit_interest remote' } do |f| %>
    <%= f.select(:user_rating, options_for_select((1..10), interest.user_rating), 
    {}, class: 'current-user-rating-options hide input-mini input-xmini', data: { activity_id: a.id } )%>
		<%= f.submit 'Add', class: 'btn' %>
	<% end %>
	</section>
	<section class='float-left height-mini'>
		<%= button_to 'remove', interest, method: 'delete', remote: true, 
			class: 'delete-current-activity btn-link hide', form_class: 'button_to',
			data: { activity_id: a.id, confirm: "Remove #{a.name}?", confirm_title: 'Remove'}  %>
	</section>
	<section style='clear: both'>
	</section>
</section>

app/views/interests/new.html.erb
<h1>Add Interest</h1>
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
	  <%= link_to "Back", new_user_interest_path(@user) %>
  <% else %>
      <div class="field">
        <%= f.label :activity_id %><br>
    	  <% activities_array = @activities.map { |activity| [activity.name, activity.id] } %>
        <%= f.select(:activity_id, options_for_select(activities_array)) %>
      </div>
      <div class="field">
    	  <%= f.label :user_rating %><br>
    	  <%= f.select(:user_rating, options_for_select((1..10).to_a)) %>
      </div>
      <div class='actions'><%= f.submit 'Add', class: 'btn'  %></div>
<%   end
end %>

app/views/interests/update.js.erb
$('#current-user-activties').html("<%= j render partial: 'user_interests', collection: Array(current_user.interests.sort {|x,y| x.user_rating <=> y.user_rating }).reverse, as: :interest %>")
$("#activity-options").html("<%= j render partial: 'add_interest', collection: Activity.all, as: :activity %>")
$('.edit_interest').editInterest()
$('.new_interest').editInterest()
$('.on-click').addOnClickActivities()
$('#flash').html("<%= j raw(flash_display) %>")
$('.flash').flashExitListen()