config/routes.rb
Bk::Application.routes.draw do

  get "event_images/index"

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: 'authentications#failure'
  match 'auth/:provider/returning', to: 'authentications#returning'
  get 'authentications' => 'authentications#index'
  get 'register' => 'users#new'
  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'home' => 'users#show'
  get 'edit' => 'users#edit'
  get 'activities' => 'activities#index'
  match '/activities/:activity_id/places/:place_id/images(.:format)', to: 'place_images#index'
  get '/users/:user_id/images(.:format)', to: 'user_images#index'
  get '/users/:user_id/images/:id(.:format)', to: 'user_images#update'
  match '/activities/:activity_id/places/:place_id/events/:id(.:format)', to: 'place_events#show'
  
  post '/users/:user_id/images(.:format)' => 'user_images#create', as: :new_user_image
  delete '/users/:user_id/images/:id(.:format)' => 'user_images#destroy'
  
  get '/activities/:activity_id/places/:place_id/events/:id/images(.:format)', to: 'event_images#index'

  
  resources :sessions
  resources :interests
  resources :password_resets
  
  resources :activities do
    resources :places do
      resources :images
      resources :events do
        resources :images
      end
    end
  end
  
  resources :users do
    resources :interests
    resources :activities
    resources :events
    resources :comments
    resources :images
  end
  
  
  

  root :to => "sessions#new"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :user_id, :user_rating
  has_many :interests
  has_many :users, :through => :interests
  has_many :places
  has_many :images
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :image_url, :provider, :sent_at, :uid
  belongs_to :user
  validates :provider, uniqueness: { scope: :uid }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :place_id, :text, :user_id, :event_id
  belongs_to :user
  belongs_to :place
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description, :place_id, :recurring, :time, :title
  has_many :comments
  has_many :images
  belongs_to :place
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :type, :url, :place_id, :event_id, :user_id, :activity_id, :rating, :image_type, :title, :description, :image, :remote_image_url
  belongs_to :place
  belongs_to :activity
  belongs_to :user
  belongs_to :event
  mount_uploader :image, ImageUploader
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  attr_accessible :activity_id, :user_rating
  validates :activity_id, uniqueness: { scope: :user_id }
end

app/models/permissions.rb
module Permissions
  def self.permission_for(user)
    if user.nil?
      GuestPermission.new
    elsif user.is_admin?
      AdminPermission.new(user)
    else
      MemberPermission.new(user)
    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :activity_id, :directions, :hours, :location, :zip_code
  has_many :comments
  has_many :images
  has_many :events
  belongs_to :activity
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_many :interests
  has_many :activities, :through => :interests
  has_many :authentications
  has_many :comments
  has_many :images
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation, :zip_code, :is_admin, :username
  validates_uniqueness_of :email
  validates :email, :presence => true, :email => true
  #validates :password, :length => { :minimum => 8 }
  # each User.new creates calls generate_token and stores it in :auth_token
  before_create { generate_token(:auth_token) }
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
  end
  
  def new
  end
  
  def show
    @place = current_resource
    @default_images = Array(Image.where(place_id: current_resource, image_type: 'default').sort{|x,y| x.rating <=> y.rating }).reverse
    @banner_images =  Array(Image.where(activity_id: current_resource.activity_id, image_type: 'banner' ).sort{|x,y| x.rating <=> y.rating }).reverse
    @comments = @place.comments
    @comment = Comment.new
  end
  
private
  def current_resource
    @current_resource ||= Place.find(params[:id]) if params[:id]
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activties_helper.rb
module ActivtiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_images_helper.rb
module EventImagesHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
  
  # Flash Helper
  def flash_display
    response = ""
    flash.each do |name, msg|
      response = response + content_tag(:div, msg, :id => "flash_#{name}")
    end
    response.insert(0, "<i class='icon-remove pull-right' id='flash-exit'></i>" )
    flash.discard
    response
  end
  
end

app/helpers/place_events_helper.rb
module PlaceEventsHelper
end

app/helpers/place_images_helper.rb
module PlaceImagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/places/_info.html.erb
<ul class='info-list'>
  <li><span class='info-title'>Location: </span><span class='info-text'><%= place.location %></span></li>
  <li><span class='info-title'>Hours: </span><span class='info-text'><%= place.hours %></span></li>
  <li><span class='info-title'>Directions: </span><span class='info-text'><%= place.directions %></span></li>
  <li><span class='info-title'>Events: </span>
    <% place.events.each_with_index do |event, index = 0 | %>
      <% if index == 0 %>
          <span class='info-text'><%= link_to event.title, activity_place_event_path(place.activity,event) %></span>
        <% else %>
          <span class='info-text'>, <%= link_to event.title, activity_place_event_path(place.activity,event) %></span>
        <% end %>
    <% end %>
  </li> 
</ul>

app/views/places/_thumbnail.html.erb
<% if thumbnail_counter < 5 %>
  <a class='image-modal-link' href="#image-modal" role="button" data-toggle="modal" data-image-frame="<%= thumbnail_counter %>">
    <%= image_tag thumbnail.image_url(:thumb), class: 'place-thumbnail img-rounded hover-gray' if thumbnail.image? %>
  </a>
<% end %>

app/views/places/show.html.erb
<section id='place-banner'>
  <figure class='banner-figure'>
    <figcaption>
      <h1 class='gray'>Places</h1>
    </figcaption>
    <%= image_tag @banner_images.first.image_url(:banner), class: 'banner-img' if @banner_images.first.image? %>
  </figure>
</section><!-- /#place-banner -->

<section id='place-title' class='lead'><%= @place.title %></section><!-- /#place-title -->

<section class='span12' id='map-and-info'>
  <section class='row'>
    <section class='span5'>
      <iframe class='thick-border' src="https://maps.google.com/maps?f=q&amp;sspn=0.023731,0.045447&amp;ll=21.661736,-158.048844&amp;spn=0.023732,0.045447&amp;output=embed"></iframe><br>
<small><a href="https://maps.google.com/maps?f=q&amp;sspn=0.023731,0.045447&amp;ll=21.661736,-158.048844&amp;spn=0.023732,0.045447">View Larger Map</a></small>
    </section><!-- /.span5 -->
    <section class='span6 images-and-info'>
      <section class='span6 thumbnails'>
        <%= render partial: 'thumbnail', collection: @default_images, locals: { place: @place } %>
      </section><!-- /.thumnails -->
      <section id='view-all-thumbnails'>
        <%= link_to 'view all', activity_place_images_path(@place.activity,@place), class: '' %>
      </section><!-- /#view-all-thumbnails -->
      <section class='modal'>
        <%= render partial: 'images/modal', locals: { images: @default_images, resource: @place } %>
      </section>
      <section id='place-info-wrap'>
        <%= render partial: 'info', locals: { place: @place } %>
      </section><!-- /#info-wrap -->
    </section><!-- /.images-and-info -->
  </section><!--/.row -->
</section><!--/.map-and-info -->

<section clas'span11 clean-border comments'>
  <%= render partial: 'comments/place_comments', locals: { comments: @comments, comment: @comment, resource: @place }  %>
</section><!-- /.comments -->